spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring.json.value.default.type: "java.util.HashMap"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/homebite_payments
    username: postgres
    password: root204
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082

razorpay:
  key-id: rzp_test_S4wJ9OE3aYueRA
  key-secret: LUCcJeyVpNo4aZzPzI7E7DJm

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

order-service:
  url: http://localhost:8083

gateway:
  internal-secret: 7qWThFMxHS6gPtr56lda9GGWCQuyAxSALjNBvCK5Bn9/kB+n1Twz2bFCGPiAQAvoMgQ8b24PXIKMMUvuoQ4yow==