spring:
  application:
    name: Gateway


  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=2

        - id: menu-services
          uri: http://localhost:8086
          predicates:
            - Path=/api/providers/menu/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=3

              

        - id: provider-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/providers/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=2


        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=1

        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=1


        - id: subscription-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/subscriptions/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=1





jwt:
  secret: 1I5pSxrZT2KX4kOwW2OQKwwHhYVVBRQpkp0gjSaJh9Q/QUu4MvIwsLPSo6aOz4qm4ruKfe9rpArf5Ce+Utxdpg==


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


gateway:
  internal-secret: 7qWThFMxHS6gPtr56lda9GGWCQuyAxSALjNBvCK5Bn9/kB+n1Twz2bFCGPiAQAvoMgQ8b24PXIKMMUvuoQ4yow==




server:
  port: 8080


