spring:
  application:
    name: Gateway


  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=2

        - id: menu-services
          uri: http://localhost:8086
          predicates:
            - Path=/api/providers/menu/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=3

              

        - id: provider-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/providers/**
          filters:
            - JwtCookieToHeaderFilter
            - StripPrefix=2










jwt:
  secret: jdWWfrI4snlyFi2AfNY0tVgjJgZkDqdD+EV3YauOqzP4xRXWRjXvONNyA8AEFNoKh6p3VsxBA1mGqDm2d/punQ==


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8080


